CREATE DATABASE hibernate;

GRANT ALL PRIVILEGES ON hibernate.* TO 'root'@'localhost';

CREATE USER 'hibernate'@'localhost'
  IDENTIFIED BY 'hibernate';
GRANT ALL PRIVILEGES ON *.* TO 'hibernate'@'localhost';
FLUSH PRIVILEGES;


CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID   INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMPLOYEE_NAME VARCHAR(32) NOT NULL,
  DEPARTMENT_ID INT         NOT NULL,
  ADDRESS_ID    INT         NOT NULL,
  UNIQUE (EMPLOYEE_ID),
  INDEX (DEPARTMENT_ID),
  INDEX (ADDRESS_ID),
  FOREIGN KEY (DEPARTMENT_ID)
  REFERENCES DEPARTMENT (DEPARTMENT_ID),
  FOREIGN KEY (ADDRESS_ID)
  REFERENCES ADDRESS (ADDRESS_ID)
);

CREATE TABLE ADDRESS (
  ADDRESS_ID      INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ADDRESS_DETAILS VARCHAR(32) NOT NULL,
  EMPLOYEE_ID     INT NOT NULL,
  UNIQUE (ADDRESS_ID),
  INDEX (ADDRESS_ID),
  FOREIGN KEY (EMPLOYEE_ID)
  REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

CREATE TABLE DEPARTMENT (
  DEPARTMENT_ID      INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DEPARTMENT_DETAILS VARCHAR(32) NOT NULL,
  EMPLOYEE_ID     INT NOT NULL,
  UNIQUE (DEPARTMENT_ID) ,
  FOREIGN KEY (EMPLOYEE_ID)
  REFERENCES EMPLOYEE (EMPLOYEE_ID)
);